# Generated by Django 5.0.6 on 2024-07-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=30)),
                ('tipo_conexao', models.CharField(choices=[('MQTT', 'MQTT'), ('RABBITMQ', 'RabbitMQ'), ('SERIAL', 'Serial')], default='SERIAL', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=30)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('ultima_manutencao', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('primeiro_nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Reles',
            fields=[
                ('dispositivos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.dispositivos')),
                ('estaLigado', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cadastros.dispositivos',),
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('dispositivos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastros.dispositivos')),
                ('tipo', models.CharField(choices=[('TEMPERATURA', 'Temperatura'), ('UMIDADE', 'Umidade'), ('PRESSAO', 'Pressão')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('cadastros.dispositivos',),
        ),
        migrations.CreateModel(
            name='Microcontrolador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=30)),
                ('atual_codigo', models.TextField()),
                ('tipo_microcontrolador', models.CharField(choices=[('ESP32', 'ESP32'), ('ARDUINO_UNO', 'Arduino Uno'), ('ARDUINO', 'Arduino')], default='ARDUINO', max_length=20)),
                ('conexao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.conexao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastros.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Acessos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('nivel_acesso', models.CharField(choices=[('TOTAL', 'Total'), ('VISUALIZAR', 'Visualizar'), ('ALTERAR_VISUALIZAR', 'Alterar e Visualizar')], default='Total', max_length=20)),
                ('microcontrolador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.microcontrolador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tipo_leitura', models.CharField(choices=[('TEMPERATURA', 'Temperatura'), ('UMIDADE', 'Umidade'), ('PRESSAO', 'Pressão')], max_length=20)),
                ('valor', models.CharField(max_length=50)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
