# Generated by Django 5.0.6 on 2024-10-21 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessos',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='acessos',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='conexao',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='conexao',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='leitura',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='leitura',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='microcontrolador',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='microcontrolador',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizado_por', to='cadastros.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criado_por', to='cadastros.usuario'),
        ),
    ]
